name: wf-develop-deploy

on: 
  push:
    branches:
      - develop

jobs:
  develop-build-job:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install parcel

      - name: Build Website With Parcel
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./"

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dev"
          name: "develop-artifact"

  develop-deploy-job:
    name: Deploy to GitHub Pages
    needs: develop-build-job
    environment: development
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Artifacts to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "develop-artifact"
