name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Linting Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install htmlhint stylelint
      - name: Lint HTML
        run: npx htmlhint src/**/*.html
      - name: Lint CSS
        run: npx stylelint "styles/**/*.css"

  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install parcel
      - name: Build website
        run: npx parcel build src/index.html
